version: '3'

vars:
  IMAGE_NAME: retroarch-builder
  BUILD_DIR: ./build/RetroArch

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build RetroArch Docker image and extract files
    cmds:
      - task: docker-build
      - task: extract-files
      - task: copy-configs
      - task: list-output
#    silent: true

  docker-build:
    desc: Build the RetroArch Docker image
    cmds:
      - echo "Building RetroArch Docker image..."
      - docker build -t {{.IMAGE_NAME}} .
    silent: true

  extract-files:
    desc: Extract files from Docker container
    vars:
      CONTAINER_ID:
        sh: docker create {{.IMAGE_NAME}}
    cmds:
      - echo "Creating temporary container..."
      - mkdir -p {{.BUILD_DIR}}
      - echo "Copying files from container..."
      - docker cp {{.CONTAINER_ID}}:/home/builder/out/. {{.BUILD_DIR}}/
      - echo "Cleaning up container..."
      - docker rm {{.CONTAINER_ID}}
    silent: true

  copy-configs:
    desc: Copy configuration files
    cmds:
      - cp retroarch.cfg {{.BUILD_DIR}}
      - cp launch.sh {{.BUILD_DIR}}
    silent: true

  list-output:
    desc: List the build output
    cmds:
      - echo "Build completed! Files copied to {{.BUILD_DIR}}"
      - ls -la {{.BUILD_DIR}}
    silent: true

  cleanup:
    desc: Clean up build directory
    cmds:
      - rm -rf {{.BUILD_DIR}} || true
    silent: true

  clean:
    desc: Clean up build directory and Docker image
    cmds:
      - task: cleanup
      - docker rmi {{.IMAGE_NAME}} || true
    silent: true

  adb:
    cmds:
      - adb push {{.BUILD_DIR}} /mnt/SDCARD/System
      - say Finished deploying RetroArch!