version: '3'

vars:
  CORES: snes9x,genesis_plus_gx,gambatte,fceumm,nestopia,pcsx_rearmed,mgba,gpsp

tasks:
  clean:
    desc: Clean build artifacts and Docker images
    cmds:
      - rm -rf build/
      - docker rmi retroarch-base:latest 2>/dev/null || true
      - docker rmi retroarch-tg5040:latest 2>/dev/null || true
      - |
        for core in $(echo "{{.CORES}}" | tr ',' ' '); do
          docker rmi retroarch-core-$core:latest 2>/dev/null || true
        done
      - docker system prune -f

  build-base:
    desc: Build the base image with SDL2 preinstalled
    cmds:
      - docker build -f Dockerfiles/base.Dockerfile -t retroarch-base:latest .

  build-retroarch:
    desc: Build RetroArch executable
    deps: [ build-base ]
    cmds:
      - docker build -f Dockerfiles/retroarch.Dockerfile -t retroarch-tg5040:latest .
      - mkdir -p build/RetroArch/lib
      - docker create --name retroarch-temp retroarch-tg5040:latest
      - docker cp retroarch-temp:/home/builder/out/retroarch build/RetroArch/ 2>/dev/null || true
      - docker cp retroarch-temp:/home/builder/out/lib/libxkbcommon.so.0 build/RetroArch/lib/ 2>/dev/null || true
      - docker rm retroarch-temp

  build-core:
    desc: Build a specific core (use CORE=corename)
    deps: [ build-base ]
    requires:
      vars: [ CORE ]
    cmds:
      - docker build -f Dockerfiles/cores/{{.CORE}}.Dockerfile -t retroarch-core-{{.CORE}}:latest .
      - docker create --name core-temp-{{.CORE}} retroarch-core-{{.CORE}}:latest
      - mkdir -p build/RetroArch/cores/info build/RetroArch/lib
      - docker cp core-temp-{{.CORE}}:/home/builder/out/. build/RetroArch/cores/ 2>/dev/null || true
      - docker rm core-temp-{{.CORE}}

  build-all-cores:
    desc: Build all emulator cores sequentially
    deps: [ build-base ]
    cmds:
      - |
        echo "Building all cores: {{.CORES}}"
        for core in $(echo "{{.CORES}}" | tr ',' ' '); do
          echo "=== Building core: $core ==="
          task build-core CORE=$core || true
        done


  build-cores-parallel:
    desc: Build all cores in parallel (faster but uses more resources)
    deps: [ build-base ]
    cmds:
      - |
        echo "Building cores in parallel: {{.CORES}}"
        echo "{{.CORES}}" | tr ',' '\n' | xargs -I {} -P 4 sh -c 'echo "Building {}" && task build-core CORE={} || true'

  package:
    desc: Package RetroArch for NextUI (and similar variants)
    cmds:
      - rm -rf build/RetroArch.pak
      - mkdir -p build/RetroArch.pak
      - rm -rf build/RetroArch/cores/lib/ || true
      - cp -R build/RetroArch/ build/RetroArch.pak/
      - mkdir -p build/RetroArch.pak/cores/.info
      - mv build/RetroArch.pak/cores/info/* build/RetroArch.pak/cores/.info/ 2>/dev/null || true
      - rmdir build/RetroArch.pak/cores/info 2>/dev/null || true
      - cp scripts/launch.sh pak.json build/RetroArch.pak/
      - cp configs/retroarch-base.cfg build/RetroArch.pak/retroarch.cfg

  adb:
    cmds:
      - adb push build/RetroArch.pak /mnt/SDCARD/Tools/tg5040